spring.application.name=demo_company_system
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql:testdb
spring.datasource.username=usermaster_user
spring.datasource.password=pass
logging.level.com.example.todolist=DEBUG
logging.level.root=INFO