spring.application.name=Usermaster-1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql:testdb
spring.datasource.username=usermaster_user
spring.datasource.password=pass